# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# Use CocoaPods CDN
source 'https://cdn.cocoapods.org/'

target 'Runner' do
  use_frameworks!
  
  # Firebase pods
  pod 'Firebase', '~> 11.0'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end